name: Rust setup
description: Installs Rust toolchain and caches cargo build artifacts.

runs:
  using: composite
  steps:
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    - uses: actions/cache@v6
      with:
        path: |
          ~/.dylint_drivers/
          ~/.rustup/toolchains/
          target/dylint/
        key: dylint-${{ runner.os }}-${{ hashFiles('dylint.toml') }}
        restore-keys: dylint-${{ runner.os }}-

    - uses: actions/cache@v6
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/registry/src/
          ~/.cargo/git/db/
          ~/.cargo/git/checkouts/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-

    - name: Install cargo-nextest
      uses: taiki-e/install-action@nextest
      with:
        tool: cargo-dylint,dylint-link,cargo-nextest
