//! `strict-lints`: portable dylint lints shared across the owner's Rust
//! projects. See `lints/README.md` for adoption.

#![feature(rustc_private)]
#![warn(unused_extern_crates)]
// `rustc_private` crates come from the sysroot (`rustc-dev` component of the
// pinned nightly), not crates.io — see `lints/rust-toolchain.toml`.
extern crate rustc_lint;
extern crate rustc_session;

dylint_linting::dylint_library!();

/// Registers this library's lints with the compiler.
///
/// Each lint module exposes its own `register_lints`, generated by
/// `dylint_linting::impl_late_lint!` under the `constituent` feature — the
/// shape of dylint's `examples/general` library. The dylint driver resolves
/// the `#[unsafe(no_mangle)]` symbol below by name in the built library, and
/// it delegates to the per-lint registrations.
#[expect(clippy::no_mangle_with_rust_abi)]
#[unsafe(no_mangle)]
pub fn register_lints(sess: &rustc_session::Session, lint_store: &mut rustc_lint::LintStore) {
    // Configurable lints read this session's `dylint.toml` through the
    // process-global config table; initialize before any registration.
    // (`init_config` is idempotent — the per-lint registrations call it too.)
    dylint_linting::init_config(sess);
    bool_params::register_lints(sess, lint_store);
    error_display::register_lints(sess, lint_store);
    error_no_string::register_lints(sess, lint_store);
    no_sleep_in_tests::register_lints(sess, lint_store);
    no_sync_io::register_lints(sess, lint_store);
    panics_doc_debt::register_lints(sess, lint_store);
    require_thiserror::register_lints(sess, lint_store);
    wire_boundary::register_lints(sess, lint_store);
}

mod bool_params;
mod error_display;
mod error_no_string;
mod globs;
mod no_sleep_in_tests;
mod no_sync_io;
mod panics_doc_debt;
mod require_thiserror;
mod wire_boundary;
